language: python
services:
  - postgresql
install: 
  - pip install -r ./app/requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create database testsnp;' -U postgres
  - cd app/
script: pytest --cov-report term-missing --cov .
after_success:
  coveralls