language: python
services:
  - postgresql
before_script:
  - psql -c 'create database testsnp;' -U postgres
install: "pip install -r ./app/requirements.txt"
script: pytest --cov-report term-missing --cov ./app/